TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Futjikato.PageFreeze': ['NodeTypes/*']
    modules:
      management:
        submodules:
          pageFreezeModule:
            label: 'Page freezer'
            controller: 'Futjikato\PageFreeze\Controller\BackendController'
            description: 'Page archive to list and unarchive pages'
            icon: 'icon-archive'
            privilegeTarget: 'Futjikato.PageFreeze:BackendModule'