TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          'Futjikato.PageArchive': ['NodeTypes/*']
    modules:
      management:
        submodules:
          pageArchiveModule:
            label: 'Page archive'
            controller: 'Futjikato\PageArchive\Controller\BackendController'
            description: 'Page archive to list and unarchive pages'
            icon: 'icon-archive'
            privilegeTarget: 'Futjikato.PageArchive:BackendModule'